import { Color } from "../styles/Color";

export const Level1 = Object.freeze({
    map: {
        key: "map",
        tilesetName: "scifi-tileset",
        tilesetKey: "tiles",
        layers: [
            {
                layerID: "ground",
                collidePlayer: false,
                collideEnemies: false,
                collideBullets: false,
            },
            {
                layerID: "walls",
                collidePlayer: true,
                collideEnemies: true,
                collideBullets: true,
                collisionProperty: "blocking", // set as custom property in tiled
            },
        ],
    },
    weapons: [
        {
            name: "Pistol",
            damage: 3,
            bulletSpeed: 500,
            ttl: 300,
            cooldown: 300,
            texture: "pistol",
            scale: 1,
            pickUpScale: 0.5,
            bulletTexture: "bullet2",
            magazine: 8,
            reloadTime: 500,
            fireSoundKey: "sniper-rifle-shot",
        },
        {
            name: "Machine Gun",
            damage: 1,
            bulletSpeed: 500,
            ttl: 200,
            cooldown: 100,
            texture: "machine-gun",
            scale: 1,
            pickUpScale: 0.25,
            bulletTexture: "bullet",
            magazine: 20,
            reloadTime: 800,
            fireSoundKey: "sniper-rifle-shot",
        },
        {
            name: "Sniper Rifle",
            damage: 10,
            bulletSpeed: 1000,
            ttl: 1000,
            cooldown: 500,
            texture: "sniper-rifle",
            scale: 1,
            pickUpScale: 0.25,
            bulletTexture: "bullet",
            magazine: 5,
            reloadTime: 1000,
            fireSoundKey: "sniper-rifle-shot",
        },
    ],
    player: {
        x: 250,
        y: 500,
        health: 4,
        maxHealth: 4,
        hitInvicibilityTimeout: 800,
        hitFreezeTimeout: 100,
        texture: "player",
        scale: 2,
        speed: 300,
    },
    enemyWeapons: [
        {
            name: "Pistol",
            damage: 1,
            bulletSpeed: 100,
            ttl: 2000,
            cooldown: 500,
            texture: "pistol",
            scale: 1,
            pickUpScale: 0.5,
            bulletTexture: "bullet2",
            magazine: 8,
            reloadTime: 1000,
            fireSoundKey: "sniper-rifle-shot",
        },
    ],
    enemies: [
        {
            name: "RoBot",
            damage: 1,
            texture: "robot",
            dropFrequency: 10, // on average, one in dropFrequency kills will drop something
            health: 5,
            speed: 125,
            scale: 1,
            score: 10,
            attackRange: 0,
        },
        {
            name: "RangeBot",
            damage: 1,
            texture: "robot",
            dropFrequency: 10, // on average, one in dropFrequency kills will drop something
            health: 5,
            speed: 200,
            scale: 1,
            score: 10,
            attackRange: 200,
            weapon: "Pistol",
            tint: Color.Green,
        },
        {
            name: "FastBot2k",
            damage: 1,
            texture: "robot",
            dropFrequency: 10, // on average, one in dropFrequency kills will drop something
            health: 1,
            speed: 220,
            scale: 1,
            score: 10,
            tint: "#0000FF", // blue
            attackRange: 0, // = max distance to attack the player
        },
        {
            name: "MegaBot",
            damage: 2,
            texture: "robot",
            dropFrequency: 2,
            health: 20,
            speed: 50,
            scale: 3,
            score: 30,
            attackRange: 0,
        },
        {
            name: "DestroBot",
            damage: 3,
            texture: "robot",
            dropFrequency: 1,
            health: 30,
            speed: 150,
            scale: 4,
            score: 200,
            tint: "#FF8D13",
            attackRange: 0,
        },
    ],
    spawners: [
        {
            type: "RoBot",
            x: 250,
            y: 1275,
            enemiesPerWave: 5,
            waveTimeout: 3000,
            maxConcurrentEnemies: 10,
        },
        {
            type: "RangeBot",
            x: 1250,
            y: 600,
            enemiesPerWave: 2,
            waveTimeout: 3000,
            maxConcurrentEnemies: 4,
        },
        {
            type: "RangeBot",
            x: 250,
            y: 1275,
            enemiesPerWave: 2,
            waveTimeout: 3000,
            maxConcurrentEnemies: 4,
        },
        {
            type: "FastBot2k",
            x: 1250,
            y: 600,
            enemiesPerWave: 2,
            waveTimeout: 10000,
            maxConcurrentEnemies: 2,
        },
        {
            type: "MegaBot",
            x: 1370,
            y: 1300,
            enemiesPerWave: 1,
            waveTimeout: 3000,
            maxConcurrentEnemies: 3,
        },
        {
            type: "DestroBot",
            x: 1370,
            y: 1300,
            enemiesPerWave: 1,
            waveTimeout: 30000,
            maxConcurrentEnemies: 1,
        },
    ],
    goals: {
        killEnemies: [
            {
                type: "DestroBot",
                amount: 1,
            },
            {
                type: "MegaBot",
                amount: 1,
            },
            {
                type: "FastBot2k",
                amount: 5,
            },
            {
                type: "RangeBot",
                amount: 3,
            },
            {
                type: "RoBot",
                amount: 3,
            },
        ],
    },
});
