apiVersion: apps/v1
kind: Deployment
metadata:
  name: destrobot-deployment
  labels:
    app: destrobot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: destrobot
  template:
    metadata:
      labels:
        app: destrobot
    spec:
      containers:
        - name: destrobot
          image: nonbiri/destrobot:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Service
metadata:
  name: destrobot-service
spec:
  selector:
    app: destrobot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
